[project]
name = "aton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask==3.0.3",
    "gunicorn==23.0.0",
    "libsql>=0.1.6",
    "pytest>=8.4.1",
    "werkzeug==3.0.3",
]
