on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: gcloud check
        run: gcloud info

      - name: Upload image to cloud
        run: gcloud builds submit --tag us-west1-docker.pkg.dev/aton-272204/aton-ar-repo/aton:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-west1-docker.pkg.dev/aton-272204/aton-ar-repo/aton:latest --region us-west1 --allow-unauthenticated --project aton-272204 --max-instances=4
